# Generated by Django 4.1.7 on 2023-04-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('Dn', 'Done'), ('Pr', 'In Progress'), ('Pn', 'Pending')], max_length=2)),
                ('resources', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
