# Generated by Django 4.1.7 on 2023-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('Pending', 'Pending')], max_length=50),
        ),
    ]
