# Generated by Django 4.1.7 on 2023-04-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('Pending', 'Pending')], max_length=50)),
                ('resources', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
